name = "siteredirects"
main = "worker.js"
compatibility_date = "2025-08-21"
preview_urls = false
send_metrics = false
workers_dev = false

[[kv_namespaces]]
binding = "REDIRECTS"
id = ""

[vars]
FALLBACK_URL = "https://www.twitch.tv/socksthewolf"
